### PR TITLE
Fix #13 : change directory name "BitZeny" to "BitZenyPlus"

### LINKED ISSUE #13: ディレクトリ名等を "BitZeny" ⇒ "BitZenyPlus" にしてはどうか
`util.cpp`

- BITCOIN_CONF_FILENAME
- BITCOIN_PID_FILENAME
- GetDefaultDataDir()

`s/BitZeny/BitZenyPlus/g`
`s/bitzeny/bitzenyplus/g`

### PR DESCRIPTION
**Pull request by bellflower2015**
Fix #13

### CODE REVIEW

**Comment by cryptozeny** [comment]
title, there is not enough information on this.

the title should be change like:

```
fix #13 change directory name "BitZeny" to "BitZenyPlus"
```

what do you think?

plz see the others:
https://github.com/bitcoin/bitcoin/pulls

**Comment by bellflower2015** [comment]
thx for advice!

**Comment by nao20010128nao** [comment]
LGTM

**Review by Lesmiscore — APPROVED** [review]
Ok

**Comment by cryptozeny** [comment]
i will test it

**Comment by cryptozeny** [comment]
i think the `branch name` also should be changed. `feature/13` no info about this branch 

but for now is ok.

**Comment by cryptozeny** [comment]
screenshot from 2018-08-06 22-38-17

wait please. it looks still same for me.

**Pull request merged**
