### PR TITLE
Enable TravisCI tests [need to fix unit tests first]

### PR DESCRIPTION
**Pull request by shuichiro-makigaki**
Related Issue: #9
Depends on: #37

### CODE REVIEW

**Review by onokatio — APPROVED** [review]
LGTM !

**Comment by onokatio** [comment]
(´・ω・｀)
https://travis-ci.org/bitzenyPlus/BitZenyPlus/jobs/435628299#L2260

```
FAIL: test/test_bitcoin
=======================
../build-aux/test-driver: line 107: ./test/test_bitcoin: cannot execute binary file: Exec format error
============================================================================
Testsuite summary for BitZeny Core 3.0.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/BitzenyCoreDevelopers/bitzeny/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory `/home/travis/build/bitzenyPlus/BitZenyPlus/build/bitzeny-arm-linux-gnueabihf/src'
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory `/home/travis/build/bitzenyPlus/BitZenyPlus/build/bitzeny-arm-linux-gnueabihf/src'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/home/travis/build/bitzenyPlus/BitZenyPlus/build/bitzeny-arm-linux-gnueabihf/src'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/bitzenyPlus/BitZenyPlus/build/bitzeny-arm-linux-gnueabihf/src'
make: *** [check-recursive] Error 1
/home/travis/.travis/job_stages: line 376: 23634 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
```

**Comment by cryptozeny** [comment]
this PR should be close or not? no activity for too long time... :thinking:

**Comment by cryptozeny** [comment]
it seems failed

image

**Comment by cryptozeny** [comment]
I restarted the Travis test. If it's all passing, then we can merge this.

image

**Review by cryptozeny — CHANGES_REQUESTED** [review]
If it's passing all (Travis and Unit Tests), we can merge this. But if not, we have to fix some tests first.

**Comment by cryptozeny** [comment]
its failed. so I close this PR.

image

**Comment by cryptozeny** [comment]
I'm sorry. This PR failed but does not close for the next fix.

**Comment by cryptozeny** [comment]
```
FAIL: test/test_bitcoin
=======================
../build-aux/test-driver: line 107: ./test/test_bitcoin: cannot execute binary file: Exec format error
```

we need to fix those errors first.

**Comment by cryptozeny** [comment]
its too old PR. i am closing this.

**Pull request closed without merging**
